import { expect, test, type APIRequestContext } from "@playwright/test";

/**
 * Textbook-mode API flow in mock AI mode: create a textbook course, wait for
 * the outline draft, verify fixed intro/conclusion roles, save an edit (and
 * verify a client cannot self-assert "confirmed"), confirm the outline, and
 * check that chapters are queued and the textbook map was generated by the
 * code renderer.
 */
test("textbook mode: outline draft → edit → confirm → chapters queued + map", async ({ request }) => {
  test.setTimeout(120_000);
  const headers = {
    "x-learnbyai-user-id": `textbook-flow-${crypto.randomUUID()}@example.com`,
    "Content-Type": "application/json",
  };

  const createResponse = await request.post("/api/courses", {
    headers,
    data: {
      contentMode: "textbook",
      topic: "测试教材主题",
      goal: "验证教材模式端到端流程",
      background: "具备基础编程能力",
      styles: [],
      learningMode: "standard",
      chapterCount: 5,
      difficulty: "intermediate",
    },
  });
  expect(createResponse.ok()).toBeTruthy();
  const created = await createResponse.json();
  const courseId: string = created.course?.id ?? created.id;
  expect(courseId).toBeTruthy();

  // Planning runs inline in mock mode; poll until the outline draft is ready.
  await expect.poll(async () => {
    const meta = await readOutline(request, courseId, headers);
    return meta?.outlineStatus;
  }, { timeout: 60_000 }).toBe("ready");

  const meta = await readOutline(request, courseId, headers);
  const chapters = meta.outline?.chapters ?? [];
  expect(chapters.length).toBeGreaterThanOrEqual(3);
  expect(chapters[0].fixedRole).toBe("introduction");
  expect(chapters.at(-1).fixedRole).toBe("conclusion");
  for (const chapter of chapters.slice(1, -1)) {
    expect(chapter.sections.length).toBeGreaterThan(0);
  }

  // Edit the title AND try to self-assert "confirmed" — the server must keep
  // the draft at "ready" (only the confirm endpoint mints "confirmed").
  const editedMeta = { ...meta, title: "编辑后的书名", outlineStatus: "confirmed" };
  const putResponse = await request.put(`/api/courses/${courseId}/textbook-outline`, {
    headers,
    data: { textbookMeta: editedMeta },
  });
  expect(putResponse.ok()).toBeTruthy();
  const putJson = await putResponse.json();
  expect(putJson.textbookMeta.title).toBe("编辑后的书名");
  expect(putJson.textbookMeta.outlineStatus).toBe("ready");

  const confirmResponse = await request.post(`/api/courses/${courseId}/confirm-textbook-outline`, {
    headers,
    data: {},
  });
  expect(confirmResponse.ok()).toBeTruthy();
  const confirmed = await confirmResponse.json();
  expect(confirmed.course.textbookMeta.outlineStatus).toBe("confirmed");
  expect(confirmed.jobs.length).toBeGreaterThan(0);

  // Without a user image API the map falls back to the code renderer.
  const map = confirmed.course.textbookMeta.textbookMap;
  expect(map).toBeTruthy();
  expect(map.generationMode).toBe("code");
  expect(map.status).toBe("ready");
  expect(map.url).toMatch(/^\/api\/illustrations\//);
  const mapImage = await request.get(map.url, { headers });
  expect(mapImage.ok()).toBeTruthy();
  expect(mapImage.headers()["content-type"]).toContain("image/svg+xml");

  // Every non-ready chapter should be queued for generation.
  const courseAfter = (await (await request.get(`/api/courses/${courseId}`, { headers })).json()).course;
  const queued = courseAfter.chapters.filter((chapter: { status?: string }) => chapter.status === "queued");
  expect(queued.length).toBeGreaterThan(0);
});

async function readOutline(request: APIRequestContext, courseId: string, headers: Record<string, string>) {
  const response = await request.get(`/api/courses/${courseId}/textbook-outline`, { headers });
  if (!response.ok()) return undefined;
  return (await response.json()).textbookMeta;
}
